Config.Inventory = {}
Config.Inventory.Objects = {
    ['default'] = 'hei_prop_drug_statue_box_big',
    ['money'] = 'bkr_prop_bkr_cashpile_01',
    ['weapon'] = 'gr_prop_gr_crate_pistol_02a'
}

Config.Inventory.Components = {
    --- Pistols
    ['weapon_pistol'] = {
        ['suppresor'] = 'COMPONENT_AT_PI_SUPP_02',
        ['extclip'] = 'COMPONENT_PISTOL_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_PI_FLSH',
        ['skin'] = 'COMPONENT_PISTOL_VARMOD_LUXE',
    },
    ['weapon_combatpistol'] = {
        ['extclip'] = 'COMPONENT_COMBATPISTOL_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_PI_FLSH',
        ['suppresor'] = 'COMPONENT_AT_PI_SUPP',
        ['skin'] = 'COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER',
    },
    ['weapon_appistol'] = {
        ['extclip'] = 'COMPONENT_APPISTOL_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_PI_FLSH',
        ['suppresor'] = 'COMPONENT_AT_PI_SUPP',
        ['skin'] = 'COMPONENT_APPISTOL_VARMOD_LUXE',
    },
    ['weapon_pistol50'] = {
        ['extclip'] = 'COMPONENT_PISTOL50_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_PI_FLSH',
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP_02',
        ['skin'] = 'COMPONENT_PISTOL50_VARMOD_LUXE',
    },
    ['weapon_revolver'] = {
        ['skin'] = 'COMPONENT_PISTOL50_VARMOD_LUXE',
    },
    ['weapon_snspistol'] = {
        ['extclip'] = 'COMPONENT_SNSPISTOL_CLIP_02',
        ['skin'] = 'COMPONENT_SNSPISTOL_VARMOD_LOWRIDER',
    },
    ['weapon_heavypistol'] = {
        ['extclip'] = 'COMPONENT_HEAVYPISTOL_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_PI_FLSH',
        ['suppresor'] = 'COMPONENT_AT_PI_SUPP',
        ['skin'] = 'COMPONENT_HEAVYPISTOL_VARMOD_LUXE',
    },
    ['weapon_revolver_mk2'] = {
        ['flashlight'] = 'COMPONENT_AT_PI_FLSH',
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO_MK2',
        ['camo'] = 'COMPONENT_REVOLVER_MK2_CAMO', 
        ['camo2'] = 'COMPONENT_REVOLVER_MK2_CAMO_02', 
        ['camo3'] = 'COMPONENT_REVOLVER_MK2_CAMO_03', 
        ['camo4'] = 'COMPONENT_REVOLVER_MK2_CAMO_04', 
        ['camo5'] = 'COMPONENT_REVOLVER_MK2_CAMO_05', 
        ['camo6'] = 'COMPONENT_REVOLVER_MK2_CAMO_06', 
        ['camo7'] = 'COMPONENT_REVOLVER_MK2_CAMO_07', 
        ['camo8'] = 'COMPONENT_REVOLVER_MK2_CAMO_08', 
        ['camo9'] = 'COMPONENT_REVOLVER_MK2_CAMO_09', 
        ['camo10'] = 'COMPONENT_REVOLVER_MK2_CAMO_010', 
        ['camo11'] = 'COMPONENT_REVOLVER_MK2_CAMO_IND_01', 
    },  
    ['weapon_snspistol_mk2'] = {
        ['extclip'] = 'COMPONENT_SNSPISTOL_MK2_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_PI_FLSH_03',
        ['suppresor'] = 'COMPONENT_AT_PI_SUPP_02',
        ['scope'] = 'COMPONENT_AT_PI_RAIL',
        ['camo'] = 'COMPONENT_SNSPISTOL_MK2_CAMO', 
        ['camo2'] = 'COMPONENT_SNSPISTOL_MK2_CAMO_02', 
        ['camo3'] = 'COMPONENT_SNSPISTOL_MK2_CAMO_03', 
        ['camo4'] = 'COMPONENT_SNSPISTOL_MK2_CAMO_04', 
        ['camo5'] = 'COMPONENT_SNSPISTOL_MK2_CAMO_05', 
        ['camo6'] = 'COMPONENT_SNSPISTOL_MK2_CAMO_06', 
        ['camo7'] = 'COMPONENT_SNSPISTOL_MK2_CAMO_07', 
        ['camo8'] = 'COMPONENT_SNSPISTOL_MK2_CAMO_08', 
        ['camo9'] = 'COMPONENT_SNSPISTOL_MK2_CAMO_09', 
        ['camo10'] = 'COMPONENT_SNSPISTOL_MK2_CAMO_010', 
        ['camo11'] = 'COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE', 
    },
    ['weapon_pistol_mk2'] = {
        ['suppresor'] = 'COMPONENT_AT_PI_SUPP_02',
        ['extclip'] = 'COMPONENT_PISTOL_MK2_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_PI_FLSH_02',
        ['scope'] = 'COMPONENT_AT_PI_RAIL',
        ['camo'] = 'COMPONENT_PISTOL_MK2_CAMO', 
        ['camo2'] = 'COMPONENT_PISTOL_MK2_CAMO_02', 
        ['camo3'] = 'COMPONENT_PISTOL_MK2_CAMO_03', 
        ['camo4'] = 'COMPONENT_PISTOL_MK2_CAMO_04', 
        ['camo5'] = 'COMPONENT_PISTOL_MK2_CAMO_05', 
        ['camo6'] = 'COMPONENT_PISTOL_MK2_CAMO_06', 
        ['camo7'] = 'COMPONENT_PISTOL_MK2_CAMO_07', 
        ['camo8'] = 'COMPONENT_PISTOL_MK2_CAMO_08', 
        ['camo9'] = 'COMPONENT_PISTOL_MK2_CAMO_09', 
        ['camo10'] = 'COMPONENT_PISTOL_MK2_CAMO_010', 
        ['camo11'] = 'COMPONENT_PISTOL_MK2_CAMO_IND_01', 
    },
    ['weapon_vintagepistol'] = {
        ['extclip'] = 'COMPONENT_VINTAGEPISTOL_CLIP_02',
        ['suppresor'] = 'COMPONENT_AT_PI_SUPP',
    },
    ['weapon_ceramicpistol'] = {
        ['extclip'] = 'COMPONENT_CERAMICPISTOL_CLIP_02',
        ['suppresor'] = 'COMPONENT_CERAMICPISTOL_SUPP',
    },
    --- Submachine Guns
    ['weapon_microsmg'] = {
        ['extclip'] = 'COMPONENT_MICROSMG_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_PI_FLSH',
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP_02',
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO',
        ['skin'] = 'COMPONENT_MICROSMG_VARMOD_LUXE',
    },
    ['weapon_smg'] = {
        ['extclip'] = 'COMPONENT_SMG_CLIP_02',
        ['druclip'] = 'COMPONENT_SMG_CLIP_03',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH',
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO',
        ['suppresor'] = 'COMPONENT_AT_PI_SUPP',
        ['skin'] = 'COMPONENT_SMG_VARMOD_LUXE',
    },
    ['weapon_assaultsmg'] = {
        ['extclip'] = 'COMPONENT_ASSAULTSMG_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH',
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO',
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP_02',
        ['skin'] = 'COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER',
    },
    ['weapon_minismg'] = {
        ['extclip'] = 'COMPONENT_MINISMG_CLIP_02',
    },
    ['weapon_smg_mk2'] = {
        ['extclip'] = 'COMPONENT_SMG_MK2_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH',
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2',
        ['scope_medium'] = 'COMPONENT_AT_SCOPE_SMALL_SMG_MK2',
        ['suppresor'] = 'COMPONENT_AT_PI_SUPP',
        ['camo'] = 'COMPONENT_SMG_MK2_CAMO', 
        ['camo2'] = 'COMPONENT_SMG_MK2_CAMO_02', 
        ['camo3'] = 'COMPONENT_SMG_MK2_CAMO_03', 
        ['camo4'] = 'COMPONENT_SMG_MK2_CAMO_04', 
        ['camo5'] = 'COMPONENT_SMG_MK2_CAMO_05', 
        ['camo6'] = 'COMPONENT_SMG_MK2_CAMO_06', 
        ['camo7'] = 'COMPONENT_SMG_MK2_CAMO_07', 
        ['camo8'] = 'COMPONENT_SMG_MK2_CAMO_08', 
        ['camo9'] = 'COMPONENT_SMG_MK2_CAMO_09', 
        ['camo10'] = 'COMPONENT_SMG_MK2_CAMO_010', 
        ['camo11'] = 'COMPONENT_SMG_MK2_CAMO_IND_01', 
    },
    ['weapon_machinepistol'] = {
        ['extclip'] = 'COMPONENT_MACHINEPISTOL_CLIP_02',
        ['druclip'] = 'COMPONENT_MACHINEPISTOL_CLIP_03',
        ['suppresor'] = 'COMPONENT_AT_PI_SUPP',
    },
    ['weapon_combatpdw'] = {
        ['extclip'] = 'COMPONENT_COMBATPDW_CLIP_02',
        ['druclip'] = 'COMPONENT_COMBATPDW_CLIP_03',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH',
        ['scope'] = 'COMPONENT_AT_SCOPE_SMALL',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP',        
    },
    --- Shotguns
    ['weapon_pumpshotgun'] = {
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_SR_SUPP',
        ['skin'] = 'COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER',
    },
    ['weapon_sawnoffshotgun'] = {
        ['skin'] = 'COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE',
    },
    ['weapon_assaultshotgun'] = {
        ['extclip'] = 'COMPONENT_ASSAULTSHOTGUN_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP',    
    },
    ['weapon_bullpupshotgun'] = {
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP_02',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP',    
    },
    ['weapon_pumpshotgun_mk2'] = {
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_SR_SUPP_03',
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO_MK2',
        ['scope_medium'] = 'COMPONENT_AT_SCOPE_SMALL_MK2',
        ['camo'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO', 
        ['camo2'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_02', 
        ['camo3'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_03', 
        ['camo4'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_04', 
        ['camo5'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_05', 
        ['camo6'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_06', 
        ['camo7'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_07', 
        ['camo8'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_08', 
        ['camo9'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_09', 
        ['camo10'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_010', 
        ['camo11'] = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01', 
    },
    ['weapon_heavyshotgun'] = {
        ['extclip'] = 'COMPONENT_HEAVYSHOTGUN_CLIP_02',
        ['druclip'] = 'COMPONENT_HEAVYSHOTGUN_CLIP_03',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP_02',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP',    
    },
    ['weapon_combatshotgun'] = {
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP',    
    },
    --- Assault Rifle
    ['weapon_assaultrifle'] = {
        ['extclip'] = 'COMPONENT_ASSAULTRIFLE_CLIP_02',
        ['druclip'] = 'COMPONENT_ASSAULTRIFLE_CLIP_03',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP_02',
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP',    
        ['skin'] = 'COMPONENT_ASSAULTRIFLE_VARMOD_LUXE',
    },
    ['weapon_carbinerifle'] = {
        ['extclip'] = 'COMPONENT_CARBINERIFLE_CLIP_02',
        ['druclip'] = 'COMPONENT_CARBINERIFLE_CLIP_03',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP',    
        ['scope_medium'] = 'COMPONENT_AT_SCOPE_MEDIUM',
        ['skin'] = 'COMPONENT_CARBINERIFLE_VARMOD_LUXE',
    },
    ['weapon_advancedrifle'] = {
        ['extclip'] = 'COMPONENT_ADVANCEDRIFLE_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP',
        ['scope'] = 'COMPONENT_AT_SCOPE_SMALL',
    },
    ['weapon_specialcarbine'] = {
        ['extclip'] = 'COMPONENT_SPECIALCARBINE_CLIP_02',
        ['druclip'] = 'COMPONENT_SPECIALCARBINE_CLIP_03',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP_02',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP',    
        ['scope_medium'] = 'COMPONENT_AT_SCOPE_MEDIUM',
        ['skin'] = 'COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER',
    },
    ['weapon_bullpuprifle'] = {
        ['extclip'] = 'COMPONENT_BULLPUPRIFLE_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP',   
        ['scope'] = 'COMPONENT_AT_SCOPE_SMALL', 
        ['skin'] = 'COMPONENT_BULLPUPRIFLE_VARMOD_LOW',
    },
    ['weapon_bullpuprifle_mk2'] = {
        ['extclip'] = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP_02',    
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO_02_MK2', 
        ['scope_medium'] = 'COMPONENT_AT_SCOPE_SMALL_MK2', 
        ['camo'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO', 
        ['camo2'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_02', 
        ['camo3'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_03', 
        ['camo4'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_04', 
        ['camo5'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_05', 
        ['camo6'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_06', 
        ['camo7'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_07', 
        ['camo8'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_08', 
        ['camo9'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_09', 
        ['camo10'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_10', 
        ['camo11'] = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01', 
    },
    ['weapon_specialcarbine_mk2'] = {
        ['extclip'] = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP_02',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP_02',    
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO_MK2', 
        ['scope_medium'] = 'COMPONENT_AT_SCOPE_MEDIUM_MK2', 
        ['camo'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO', 
        ['camo2'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_02', 
        ['camo3'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_03', 
        ['camo4'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_04', 
        ['camo5'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_05', 
        ['camo6'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_06', 
        ['camo7'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_07', 
        ['camo8'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_08', 
        ['camo9'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_09', 
        ['camo10'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_10', 
        ['camo11'] = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01', 
    },
    ['weapon_assaultrifle_mk2'] = {
        ['extclip'] = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP_02',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP_02',    
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO_MK2', 
        ['scope_lager'] = 'COMPONENT_AT_SCOPE_MEDIUM_MK2', 
        ['camo'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO', 
        ['camo2'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_02', 
        ['camo3'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_03', 
        ['camo4'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_04', 
        ['camo5'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_05', 
        ['camo6'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_06', 
        ['camo7'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_07', 
        ['camo8'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_08', 
        ['camo9'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_09', 
        ['camo10'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_10', 
        ['camo11'] = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01', 
    },
    ['weapon_carbinerifle_mk2'] = {
        ['extclip'] = 'COMPONENT_CARBINERIFLE_MK2_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP_02',    
        ['scope'] = 'COMPONENT_AT_SCOPE_MACRO_MK2', 
        ['scope_lager'] = 'COMPONENT_AT_SCOPE_MEDIUM_MK2', 
        ['camo'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO', 
        ['camo2'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO_02', 
        ['camo3'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO_03', 
        ['camo4'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO_04', 
        ['camo5'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO_05', 
        ['camo6'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO_06', 
        ['camo7'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO_07', 
        ['camo8'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO_08', 
        ['camo9'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO_09', 
        ['camo10'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO_10', 
        ['camo11'] = 'COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01', 
    },
    ['weapon_compactrifle'] = {
        ['extclip'] = 'COMPONENT_COMPACTRIFLE_CLIP_02',
        ['druclip'] = 'COMPONENT_COMPACTRIFLE_CLIP_03',
    },
    ['weapon_militaryrifle'] = {
        ['extclip'] = 'COMPONENT_MILITARYRIFLE_CLIP_02',
        ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
        ['suppresor'] = 'COMPONENT_AT_AR_SUPP',
        ['scope'] = 'COMPONENT_AT_SCOPE_SMALL', 
    },
    --- Light Machine Guns
    ['weapon_mg'] = {
        ['extclip'] = 'COMPONENT_MG_CLIP_02',
        ['scope'] = 'COMPONENT_AT_SCOPE_SMALL_02', 
        ['skin'] = 'COMPONENT_MG_VARMOD_LOWRIDER',
    },
    ['weapon_combatmg'] = {
        ['extclip'] = 'COMPONENT_MG_CLIP_02',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP',  
        ['scope'] = 'COMPONENT_AT_SCOPE_SMALL_MK2', 
        ['scope_lager'] = 'COMPONENT_AT_SCOPE_MEDIUM_MK2', 
        ['skin'] = 'COMPONENT_COMBATMG_VARMOD_LOWRIDER',
    },
    ['weapon_combatmg_mk2'] = {
        ['extclip'] = 'COMPONENT_COMBATMG_MK2_CLIP_02',
        ['grip'] = 'COMPONENT_AT_AR_AFGRIP_02',  
        ['camo'] = 'COMPONENT_COMBATMG_MK2_CAMO', 
        ['camo2'] = 'COMPONENT_COMBATMG_MK2_CAMO_02', 
        ['camo3'] = 'COMPONENT_COMBATMG_MK2_CAMO_03', 
        ['camo4'] = 'COMPONENT_COMBATMG_MK2_CAMO_04', 
        ['camo5'] = 'COMPONENT_COMBATMG_MK2_CAMO_05', 
        ['camo6'] = 'COMPONENT_COMBATMG_MK2_CAMO_06', 
        ['camo7'] = 'COMPONENT_COMBATMG_MK2_CAMO_07', 
        ['camo8'] = 'COMPONENT_COMBATMG_MK2_CAMO_08', 
        ['camo9'] = 'COMPONENT_COMBATMG_MK2_CAMO_09', 
        ['camo10'] = 'COMPONENT_COMBATMG_MK2_CAMO_010', 
        ['camo11'] = 'COMPONENT_COMBATMG_MK2_CAMO_IND_01', 
    },
    ['weapon_gusenberg'] = {
        ['extclip'] = 'COMPONENT_GUSENBERG_CLIP_02',
    },
    --- Sniper Rifles
    -- ['weapon_sniperrifle'] = {
    --     ['suppresor'] = 'COMPONENT_AT_AR_SUPP_02',
    --     ['skin'] = 'COMPONENT_SNIPERRIFLE_VARMOD_LUXE',
    -- },
    -- ['weapon_marksmanrifle_mk2'] = {
    --     ['extclip'] = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_02',
    --     ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
    --     ['suppresor'] = 'COMPONENT_AT_AR_SUPP',
    --     ['grip'] = 'COMPONENT_AT_AR_AFGRIP_02',   
    -- },
    -- ['weapon_heavysniper_mk2'] = {
    --     ['extclip'] = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_02',
    --     ['suppresor'] = 'COMPONENT_AT_SR_SUPP_03',
    -- },
    -- ['weapon_marksmanrifle'] = {
    --     ['extclip'] = 'COMPONENT_MARKSMANRIFLE_CLIP_02',
    --     ['flashlight'] = 'COMPONENT_AT_AR_FLSH', 
    --     ['suppresor'] = 'COMPONENT_AT_AR_SUPP',
    --     ['grip'] = 'COMPONENT_AT_AR_AFGRIP',   
    -- },
}
