Config.Clothes.IgnoreComp = {
  { label = TR("sex"), name = "sex", value = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
  { label = TR("face"), name = "face", value = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
  { label = TR("skin"), name = "skin", value = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
  { label = TR("hair_1"), name = "hair_1", value = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
  { label = TR("hair_2"), name = "hair_2", value = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
  {
    label = TR("hair_color_1"),
    name = "hair_color_1",
    value = 0,
    min = 0,
    zoomOffset = 0.6,
    camOffset = 0.65,
  },
  {
    label = TR("hair_color_2"),
    name = "hair_color_2",
    value = 0,
    min = 0,
    zoomOffset = 0.6,
    camOffset = 0.65,
  },
  {
    label = TR("eye_color"),
    name = "eye_color",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("eyebrow_size"),
    name = "eyebrows_2",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("eyebrow_type"),
    name = "eyebrows_1",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("eyebrow_color_1"),
    name = "eyebrows_3",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("eyebrow_color_2"),
    name = "eyebrows_4",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("makeup_type"),
    name = "makeup_1",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("makeup_thickness"),
    name = "makeup_2",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("makeup_color_1"),
    name = "makeup_3",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("makeup_color_2"),
    name = "makeup_4",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("lipstick_type"),
    name = "lipstick_1",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("lipstick_thickness"),
    name = "lipstick_2",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("lipstick_color_1"),
    name = "lipstick_3",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("lipstick_color_2"),
    name = "lipstick_4",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("ear_accessories"),
    name = "ears_1",
    value = -1,
    min = -1,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("ear_accessories_color"),
    name = "ears_2",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
    textureof = "ears_1",
  },
  {
    label = TR("chest_hair"),
    name = "chest_1",
    value = 0,
    min = 0,
    zoomOffset = 0.75,
    camOffset = 0.15,
  },
  {
    label = TR("chest_hair_1"),
    name = "chest_2",
    value = 0,
    min = 0,
    zoomOffset = 0.75,
    camOffset = 0.15,
  },
  {
    label = TR("chest_color"),
    name = "chest_3",
    value = 0,
    min = 0,
    zoomOffset = 0.75,
    camOffset = 0.15,
  },
  {
    label = TR("bodyb"),
    name = "bodyb_1",
    value = 0,
    min = 0,
    zoomOffset = 0.75,
    camOffset = 0.15,
  },
  {
    label = TR("bodyb_size"),
    name = "bodyb_2",
    value = 0,
    min = 0,
    zoomOffset = 0.75,
    camOffset = 0.15,
  },
  {
    label = TR("wrinkles"),
    name = "age_1",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("wrinkle_thickness"),
    name = "age_2",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("blemishes"),
    name = "blemishes_1",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("blemishes_size"),
    name = "blemishes_2",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  { label = TR("blush"), name = "blush_1", value = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
  {
    label = TR("blush_1"),
    name = "blush_2",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("blush_color"),
    name = "blush_3",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("complexion"),
    name = "complexion_1",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("complexion_1"),
    name = "complexion_2",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  { label = TR("sun"), name = "sun_1", value = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
  { label = TR("sun_1"), name = "sun_2", value = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
  {
    label = TR("freckles"),
    name = "moles_1",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("freckles_1"),
    name = "moles_2",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("beard_type"),
    name = "beard_1",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("beard_size"),
    name = "beard_2",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("beard_color_1"),
    name = "beard_3",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
  {
    label = TR("beard_color_2"),
    name = "beard_4",
    value = 0,
    min = 0,
    zoomOffset = 0.4,
    camOffset = 0.65,
  },
}

Config.Clothes.Default = {
  male = {
    torso_1 = 15,
    torso_2 = 0,
    tshirt_1 = 15,
    tshirt_2 = 0,
    arms = 15,
    arms_2 = 0,
    glasses_1 = 0,
    glasses_2 = 0,
    helmet_1 = -1,
    helmet_2 = 0,
    mask_1 = -1,
    mask_2 = 0,
    bags_1 = 0,
    bag_color = 0,
    shoes_1 = 34,
    shoes_2 = 0,
    pants_1 = 21,
    pants_2 = 0,
    bproof_1 = 0,
    decals_1 = 0,
    chain_1 = 0,
    ears_1 = -1,
  },
  female = {
    torso_1 = 15,
    torso_2 = 0,
    tshirt_1 = 15,
    tshirt_2 = 0,
    arms = 15,
    glasses_1 = 0,
    glasses_2 = 0,
    helmet_1 = -1,
    helmet_2 = 0,
    mask_1 = -1,
    mask_2 = 0,
    bags_1 = 0,
    pants_1 = 97,
    pants_2 = 0,
    shoes_1 = 34,
    shoes_2 = 0,
    bproof_1 = 0,
    decals_1 = 0,
    chain_1 = 0,
    ears_1 = -1,
  },
}

Config.Clothes.Peds = {
  Females = {

    "a_f_m_beach_01",
    "a_f_m_bevhills_01",
    "a_f_m_bevhills_02",
    "a_f_m_bodybuild_01",
    "a_f_m_business_02",
    "a_f_m_downtown_01",
    "a_f_m_eastsa_01",
    "a_f_m_eastsa_02",
    "a_f_m_fatbla_01",
    "a_f_m_fatcult_01",
    "a_f_m_fatwhite_01",
    "a_f_m_ktown_01",
    "a_f_m_ktown_02",
    "a_f_m_prolhost_01",
    "a_f_m_salton_01",
    "a_f_m_skidrow_01",
    "a_f_m_soucent_01",
    "a_f_m_soucent_02",
    "a_f_m_soucentmc_01",
    "a_f_m_tourist_01",
    "a_f_m_tramp_01",
    "a_f_m_trampbeac_01",
    "a_f_o_genstreet_01",
    "a_f_o_indian_01",
    "a_f_o_ktown_01",
    "a_f_o_salton_01",
    "a_f_o_soucent_01",
    "a_f_o_soucent_02",
    "a_f_y_beach_01",
    "a_f_y_bevhills_01",
    "a_f_y_bevhills_02",
    "a_f_y_bevhills_03",
    "a_f_y_bevhills_04",
    "a_f_y_business_01",
    "a_f_y_business_02",
    "a_f_y_business_03",
    "a_f_y_business_04",
    "a_f_y_clubcust_01",
    "a_f_y_clubcust_02",
    "a_f_y_clubcust_03",
    "a_f_y_eastsa_01",
    "a_f_y_eastsa_02",
    "a_f_y_eastsa_03",
    "a_f_y_epsilon_01",
    "a_f_y_femaleagent",
    "a_f_y_fitness_01",
    "a_f_y_fitness_02",
    "a_f_y_genhot_01",
    "a_f_y_golfer_01",
    "a_f_y_hiker_01",
    "a_f_y_hippie_01",
    "a_f_y_hipster_01",
    "a_f_y_hipster_02",
    "a_f_y_hipster_03",
    "a_f_y_hipster_04",
    "a_f_y_indian_01",
    "a_f_y_juggalo_01",
    "a_f_y_runner_01",
    "a_f_y_rurmeth_01",
    "a_f_y_scdressy_01",
    "a_f_y_skater_01",
    "a_f_y_soucent_01",
    "a_f_y_soucent_02",
    "a_f_y_soucent_03",
    "a_f_y_tennis_01",
    "a_f_y_topless_01",
    "a_f_y_tourist_01",
    "a_f_y_tourist_02",
    "a_f_y_vinewood_01",
    "a_f_y_vinewood_02",
    "a_f_y_vinewood_03",
    "a_f_y_vinewood_04",
    "a_f_y_yoga_01",
    "a_f_y_gencaspat_01",
    "a_f_y_smartcaspat_01",
  },
  Males = {

    "a_m_m_afriamer_01",
    "a_m_m_beach_01",
    "a_m_m_beach_02",
    "a_m_m_bevhills_01",
    "a_m_m_bevhills_02",
    "a_m_m_business_01",
    "a_m_m_eastsa_02",
    "a_m_m_farmer_01",
    "a_m_m_fatlatin_01",
    "a_m_m_genfat_01",
    "a_m_m_genfat_02",
    "a_m_m_golfer_01",
    "a_m_m_hasjew_01",
    "a_m_m_hillbilly_01",
    "a_m_m_hillbilly_02",
    "a_m_m_indian_01",
    "a_m_m_ktown_01",
    "a_m_m_malibu_01",
    "a_m_m_mexcntry_01",
    "a_m_m_mexlabor_01",
    "a_m_m_og_boss_01",
    "a_m_m_paparazzi_01",
    "a_m_m_polynesian_01",
    "a_m_m_prolhost_01",
    "a_m_m_rurmeth_01",
    "a_m_m_salton_01",
    "a_m_m_salton_02",
    "a_m_m_salton_03",
    "a_m_m_salton_04",
    "a_m_m_skater_01",
    "a_m_m_skidrow_01",
    "a_m_m_socenlat_01",
    "a_m_m_soucent_01",
    "a_m_m_soucent_02",
    "a_m_m_soucent_03",
    "a_m_m_soucent_04",
    "a_m_m_stlat_02",
    "a_m_m_tennis_01",
    "a_m_m_tourist_01",
    "a_m_m_tramp_01",
    "a_m_m_trampbeac_01",
    "a_m_o_acult_01",
    "a_m_o_acult_02",
    "a_m_o_beach_01",
    "a_m_o_genstreet_01",
    "a_m_o_ktown_01",
    "a_m_o_salton_01",
    "a_m_o_soucent_01",
    "a_m_o_soucent_02",
    "a_m_o_soucent_03",
    "a_m_o_tramp_01",
    "a_m_y_acult_01",
    "a_m_y_acult_02",
    "a_m_y_beach_01",
    "a_m_y_beach_02",
    "a_m_y_beach_03",
    "a_m_y_beachvesp_01",
    "a_m_y_beachvesp_02",
    "a_m_y_bevhills_01",
    "a_m_y_bevhills_02",
    "a_m_y_breakdance_01",
    "a_m_y_busicas_01",
    "a_m_y_business_01",
    "a_m_y_business_02",
    "a_m_y_business_03",
    "a_m_y_clubcust_01",
    "a_m_y_clubcust_02",
    "a_m_y_clubcust_03",
    "a_m_y_dhill_01",
    "a_m_y_downtown_01",
    "a_m_y_eastsa_01",
    "a_m_y_eastsa_02",
    "a_m_y_epsilon_01",
    "a_m_y_epsilon_02",
    "a_m_y_gay_01",
    "a_m_y_gay_02",
    "a_m_y_genstreet_01",
    "a_m_y_genstreet_02",
    "a_m_y_golfer_01",
    "a_m_y_hasjew_01",
    "a_m_y_hiker_01",
    "a_m_y_hipster_01",
    "a_m_y_hipster_02",
    "a_m_y_hipster_03",
    "a_m_y_indian_01",
    "a_m_y_jetski_01",
    "a_m_y_juggalo_01",
    "a_m_y_ktown_01",
    "a_m_y_ktown_02",
    "a_m_y_latino_01",
    "a_m_y_methhead_01",
    "a_m_y_mexthug_01",
    "a_m_y_polynesian_01",
    "a_m_y_salton_01",
    "a_m_y_skater_01",
    "a_m_y_skater_02",
    "a_m_y_soucent_01",
    "a_m_y_soucent_02",
    "a_m_y_soucent_03",
    "a_m_y_soucent_04",
    "a_m_y_stbla_01",
    "a_m_y_stbla_02",
    "a_m_y_stlat_01",
    "a_m_y_stwhi_01",
    "a_m_y_stwhi_02",
    "a_m_y_sunbathe_01",
    "a_m_y_surfer_01",
    "a_m_y_vindouche_01",
    "a_m_y_vinewood_01",
    "a_m_y_vinewood_02",
    "a_m_y_vinewood_03",
    "a_m_y_vinewood_04",
    "a_m_y_yoga_01",
    "a_m_m_mlcrisis_01",
    "a_m_y_gencaspat_01",
    "a_m_y_smartcaspat_01",
  },
}
