function User:OpenSkinCreator()
  OpenSkin(
    function()
      Event:TriggerNet("dwb:skin:save", Skinchanger:GetSkin(), false, {
        "face",
        "skin",
        "hair_1",
        "hair_2",
        "hair_color_1",
        "hair_color_2",
        "makeup_1",
        "makeup_2",
        "makeup_3",
        "makeup_4",
        "beard_1",
        "beard_2",
        "beard_3",
        "beard_4",
      })
    end,
    false,
    {
      "face",
      "skin",
      "hair_1",
      "hair_2",
      "hair_color_1",
      "hair_color_2",
      "makeup_1",
      "makeup_2",
      "makeup_3",
      "makeup_4",
      "beard_1",
      "beard_2",
      "beard_3",
      "beard_4",
    }
  )
end
