Config.Lobby = {}
Config.Lobby.numLobbies = 4

Config.Lobby.Lobbies = {}
Config.Lobby.Modes = {
  {
    pos = vec3(35.84381, -2.47406, 817.705139),
    data = {
      name = "~b~MilitaryRP",
      mode = "militaryrp",
      players = 0,
      enabled = true,
      charType = "militaryrp",
      bucket = 10,
      ipls = {
        "sandy1",
        "sandy2",
        "sandy3",
        "sandy4",
        "sandy5",
        "sandy6",
        "military_map",
        "FOB_Geronimo_2",
        "FOB_Geronimo_2_Heli",
        "FOB_Geronimo_Props_2",
        "afghantown_buildings",
        "afghantown_foliagee",
        "afghantown_props",
        "afghantown_props_2",
        "afghantown_props_3",
        "afghantownmap",
        "air",
        "Basrah_Airport",
        "Basrah_Airport_Fence",
        "Basrah_Airport_Prop_UN",
        "BigDesertExpansion",
        "BigDesertGrass",
        "BigDesertProps",
        "BigDesertProps_2",
        "BigDesertProps_Buildings",
        "billboards",
        "borderwall",
        "bujalcity",
        "bujalcityprops",
        "Desert_Random_Towns",
        "Desert_Random_Towns_Props",
        "DesertTowns1",
        "DesertTowns1_Props",
        "DesertTowns1_Props_2",
        "DesertTowns1_Props_3",
        "FAFOB",
        "FOB_Brisco",
        "FOB_Brisco_Gate",
        "FOB_Memphis",
        "FOB_Memphis_Props",
        "fobdet",
        "FOBDrew",
        "fobnazbar2",
        "JahibVillage",
        "KPP_FIB",
        "liaoning_carrier",
        "mustafacompounds",
        "mustaforrest",
        "mustaforrest2",
        "NATO_FOB_Sandy",
        "nazbar_radar",
        "RFA_Airbase",
        "RFA_FOB_BUJAL",
        "RFA_FOB_Jahib",
        "RFAfobTown",
        "UN_FOB_Jahib",
        "ukairbase_1",
        "swamp",
        "UN_FOB_Jahib",
        "unfob_sandy",
        "unfobbasrah",
        "UNProps",
        "UNStructure",
        "US_FOB_BUJAL",
        "US_FOB_Jahib",
      },
      default = {
        charData = {

          jobs = {
            {
              grade = 1,
              job = "military",
            },
          },
        },
      },
      spawns = {
        {
          coords = Config.Default.Spawn.Coords,
          heading = Config.Default.Spawn.Heading,
        },
      },
      scripts = "militaryrp",
    },
  },
  {
    pos = vec3(30.2564087, -7.776306, 817.7242),
    data = {
      name = "~g~BoskieRP",
      players = 0,
      enabled = true,
      bucket = 11,
      mode = "boskierp",
      ipls = {
        "chemical_milo",
        "hawaiisland",
        "hawaii",
        "shmann_ehos_mlo",
        "mazebank_west_milo",
        "rfc_eastcustums_milo_",
        "rfc_eastcustums_ext",
        "eastcustums_lodlights",
        "eastcustums_distantlights",
        "melina_milo",
        "ano_novo_2022_ajna_modsdetails",
        "ano_novo_2022_ajna_mods",
        "bobo_prison_lobby_milo_",
        "bobo_prison_milo_",
        "shopszbi_milo_",
      },
      default = {},
      spawns = {
        Config.Default.Spawn,
      },
      scripts = "boskierp",
    },
  },
  {

    pos = vec3(47.40387, 8.496643, 817.6265),
    data = {
      name = "~y~ApoRP",
      players = 0,
      enabled = true,
      bucket = 11 + 1,
      mode = "aporp",
      motds = {
        "WBIJ JUZ TERAZ",
      },
      ipls = {},
      default = {},
      spawns = {
        { coords = Config.Default.Spawn.Coords, heading = 343.4 },
      },
      scripts = "aporp",
    },
  },
  {
    data = {
      name = "~b~PVP",
      players = 0,
      enabled = true,
      bucket = 14,
      mode = "pvp",
      motds = {
        "NOWE TRYBY (MM, DM, DUEL, ARENY)",
      },
      ipls = {},
      default = {},
      spawns = {
        { coords = Config.Default.Spawn.Coords, heading = 343.4 },
      },
      scripts = "pvp",
    },
    pos = vec3(52.6743774, 13.4981079, 817.591858),
  },
  {
    data = {
      name = "Trening",
      enabled = false,
      value = "training",
      players = 0,
    },
    pos = vec3(45.8877563, 20.6494751, 817.591858),
  },
}
